module.exports = {
  title: "Cho's Blog",
  description: "이해한 내용을 기록합니다",
  author: "Cho",
  siteUrl: "https://bjcho0501.github.io",
  links: {
    github: "https://github.com/BJCHO0501",
    // linkedIn: "https://linkedin.com",
    // facebook: "https://www.facebook.com",
    // twitter: "https://twitter.com",
    // x: "https://x.com",
    // instagram: "https://www.instagram.com",
    // medium: "https://medium.com",
    // blogger: "https://blogger.com",
    email: "mailto:bjcho1503@naver.com",
    // resume: "https://hudi.blog",
    // link: "https://hudi.blog",
  },
  useAbout: false,
  // See https://giscus.app/
  // giscus: {
  //   repo: "devHudi/gatsby-starter-hoodie",
  //   repoId: "MDEwOlJlcG9zaXRvcnkzNjk4NjMzNTg=",
  //   category: "Comments",
  //   categoryId: "DIC_kwDOFguqvs4ChwGy",
  //   mapping: "pathname",
  //   strict: "0",
  //   reactionsEnabled: "1",
  //   inputPosition: "bottom",
  //   lang: "en",
  // },
}
